### PR TITLE
Rename `choose` to `random_string` and make it public

### PR DESCRIPTION
**Pull request by olleicua**
context: https://bugs.ruby-lang.org/issues/18183#change-93775
Originally this was a PR against ruby/ruby but it was suggested here: https://github.com/ruby/ruby/pull/4878 that I submit it here instead.

### CODE REVIEW

**Comment by nobu** [comment]
`Random#alphanumeric` now has `chars:` optional keyword argument.
May we close this PR?

**Comment by olleicua** [comment]
ok with me :) thanks

**Comment by olleicua** [comment]
@nobu out of curiosity, do you know which ruby version will it be in?

**Comment by nobu** [comment]
I think securerandam 0.3.0 bundled with ruby 3.3.0 contains it.

**Pull request closed without merging**
